### PR TITLE
Fix lack of alignment check

### LINKED ISSUE #38: Bug: Alignment requirement from raws is ignored
~~I can't believe this hadn't been caught until now.~~ nvm it's also in #2 

(using a `WORD` should raise an error if current offset is not 4-aligned)

### PR DESCRIPTION
**Pull request by StanHash**
Fixes #38 and therefore part of #2

### CODE REVIEW

File: ColorzCore/Raws/Raw.cs [hunk 1]
```diff
@@ -15,7 +15,7 @@ class Raw
         public string Name { get; }
         private int length;
         public short Code { get; }
-        public int OffsetMod { get; }
```
Comment (Crazycolorz5) [inline ColorzCore/Raws/Raw.cs]: For compatibility (or, more importantly, the original documentation for EA) reasons, maybe keep this field.

`public int OffsetMod {get;}
public int AlignmentRequirement {get { return OffsetMod; } }
`
